---
postgres:
  image: postgres:9.5
  environment:
    POSTGRES_PASSWORD: mysecretpassword
    POSTGRES_USER: postgres
    POSTGRES_DB: flyway
   
  restart: always
  ports:
   - '5432:5432'

flyway:
  image: addteq/flyway
  links:
   - postgres
